function [x, fs] = jukebox
    path='./music';

    tracks = {...
        'Lovefool - The Cardigans', ...
        'Love Song - Rebecka T?rnqvist', ...
        'In a box - Brainpool', ...
        'Sadness part 1 - Enigma', ...
        'Sound of Silence - Simon & Garfunkle', ...
        'My baby just cares for me - Nina Simone', ...
        'I wanna go home - Sator', ...
        'Nobodys wife - Anouk', ...
        'Torn - Natali Imbruglia', ...
        'Children - Robert Miles', ...
        'Brimful of asha - Cornershop', ...
        'Justified and ancient - KLF',...
        'Bitch - Meredith Brooks', ...
    };

    files = {
        'lovefool.wav', ...
        'lovesong.wav', ...
        'in_a_box.wav', ...
        'sadness1.wav', ...
        'ssilence.wav', ...
        'mybaby.wav', ...
        'go_home.wav', ...
        'nobodys.wav', ...
        'torn.wav', ...
        'children.wav', ...
        'brimful.wav', ...
        'klf.wav', ...
        'bitch.wav', ...
    };

    choice = menu('Choose track!', tracks{:});

    if choice<1
        error('Selection canceled by user interaction')
    end

    file = fullfile(path, files{choice});
    
    [x, fs] = audioread(file);
    
    % Added during the lab-session by students
    % Exercise 3
    % pwelch(x, [], [], [], fs);
    % sound(x, fs)
    freq = [1050.05, 1250, 2850.1];
    
    % Exercise 4: fixing the frequency disturbance
    r = 0.4;
    z = exp(-1j*2*pi*[freq, -freq]/fs);
    p = exp(-1j*2*pi*[freq, -freq]/fs)*r;

    b = poly(z);
    a = poly(p);

    y = filter(b, a, x);
    pwelch(y, [], [], [], fs);
    sound(y, fs);
end
